@startuml Architecture

package "Resource Loader" {
    [NVLoader] --> [NVMeshLoader]
    [NVLoader] --> [NVVoxelLoader]
}


package "Renderer" {
    [NVRenderer] --> [NVShader]
    [NVRenderer] --> [NVShaderCache]
}

collections ".frag, .vert, or .gsl" as ShaderFiles

[NVShader] --> ShaderFiles

@enduml
